app:
  server:
    url: ${SHARED_FOLDER_URL:http://localhost:8080}
    apiPath: ${FILE_API:/1.0/files/}

logging:
  level:
    root: error
    com:
      project:
        sharedfolderclient: ${LOG_LEVEL:INFO}